name: nlptorch
channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - ipykernel
  - ipython
  - jupyter=1.0.0
  - jupyterlab
  - matplotlib
  - seaborn
  - pytorch=1.4.0
  - torchtext
  - spacy
  - pandas
  - black
